{% set name = "thermoextrap" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/thermoextrap-{{ version }}.tar.gz
  sha256: 75a61bc28d538732d55c1ba2e7275d991ff8932902fa3e0dbd64108d45844665

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.2
    - setuptools-scm >=7.0
    - pip
  run:
    - python >=3.8
    - numpy >=1.20
    - xarray >=0.16
    - sympy
    - scipy
    - cmomy >=0.4
    - custom-inherit
    - attrs
    - module-utilities >=0.2

test:
  imports:
    - thermoextrap
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/usnistgov/thermoextrap
  summary: Thermodynamic extrapolation
  description: |
    A package to perform thermodynamic extrapolation of molecular simulations.
  license: NIST-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wpk-nist-gov
